name: Verify Changed files
description: Find files that have been modified during workflow execution.
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    required: true
    default: ${{ github.token }}
  files:
    description: List of files to check for changes.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding: 
  icon: check-square
  color: white
