name: Update README.md version reference

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Display the current ref
      run: echo "${{ github.ref }}"
