name: Update release version.
on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumpversion release version.
        uses: tj-actions/bumpversion@v1
        id: bumpversion
        with:
          paths: |
            README.md
      - run: cat README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updraded from ${{ steps.bumpversion.outputs.old_version }} -> ${{ steps.bumpversion.outputs.new_version }}
          branch: feature-sync-${{ steps.bumpversion.outputs.new_version }}=
          repository: .
          # Optional commit user and author settings
          commit_user_name: GitHub Actions Bot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Author <actions@github.com>
          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true
